"""IndoPak 15-line mushaf page numbers (QUL layout #12, Qudratullah, 610pp).

`data/indopak_15_qudratullah_pages.json` maps every ayah to its first page
in the standard subcontinent 15-line mushaf. Generated by
`tools/build_indopak_pagemap.py` from the QUL layout export; tracked in git.

Used by the quran_api loader to override the API's page_number for
`text_indopak*` scripts — the quran.com API only carries Madinah-604
pages regardless of script (its `mushaf` param is ignored; probed
2026-07-11), which is the wrong grid for IndoPak books.
"""

import json
from functools import lru_cache
from pathlib import Path

INDOPAK_TOTAL_PAGES = 610

_PAGES_PATH = (
    Path(__file__).resolve().parent.parent.parent.parent
    / "data" / "indopak_15_qudratullah_pages.json"
)


@lru_cache(maxsize=1)
def load_indopak_page_map() -> dict[tuple[int, int], int]:
    """Return {(surah, ayah): page} for all 6,236 ayahs.

    Raises FileNotFoundError if the tracked map is missing — IndoPak
    builds must not silently fall back to Madinah-grid pages.
    """
    if not _PAGES_PATH.exists():
        raise FileNotFoundError(
            f"{_PAGES_PATH} missing — IndoPak builds need the 15-line page map "
            "(regenerate with tools/build_indopak_pagemap.py)."
        )
    raw = json.loads(_PAGES_PATH.read_text())
    if len(raw) != 6236:
        raise ValueError(f"IndoPak page map has {len(raw)} entries, expected 6236")
    result = {}
    for key, page in raw.items():
        s, a = key.split(":")
        result[(int(s), int(a))] = page
    return result
