#!/usr/bin/env python
"""Generate tools/quran.koplugin/renamemap.lua from the release rename map.

Source: docs/filename_map_v1.csv (the frozen filename-grammar map; N1).
Output: a Lua table old_stem -> new_stem consumed by the plugin's sidecar
auto-migration (DocSettings.updateLocation), so users' highlights/progress
follow their books across the rename sweep.

Re-run at the sweep if the grammar's pending vocabulary confirmations
change any name. Rows where old == new are omitted (nothing to migrate).

Run from repo root:  python scripts/gen_renamemap.py
"""
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV = ROOT / "docs" / "filename_map_v1.csv"
OUT = ROOT / "tools" / "quran.koplugin" / "renamemap.lua"


def main():
    if not CSV.exists():
        sys.exit(f"rename map source missing: {CSV} (docs/ is local-only; "
                 "regenerate the filename map first)")
    pairs = []
    with open(CSV, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            old, new = row["old_filename"].strip(), row["new_filename"].strip()
            if old and new and old != new:
                pairs.append((old, new))
    pairs.sort()
    dupes = len(pairs) - len({o for o, _ in pairs})
    if dupes:
        sys.exit(f"{dupes} duplicate old_filename stems — map is ambiguous")

    lines = [
        "-- GENERATED by scripts/gen_renamemap.py from the release rename map",
        "-- (filename grammar v1). old filename stem -> new filename stem.",
        "-- Consumed by the plugin's sidecar migration; regenerate at the",
        "-- rename sweep. Do not edit by hand.",
        "return {",
    ]
    for old, new in pairs:
        lines.append(f'    ["{old}"] = "{new}",')
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{OUT}: {len(pairs)} rename entries")


if __name__ == "__main__":
    main()
